import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LeftSidebar from "../components/LeftSidebar";
import Bottombar from "../components/Bottombar";
import Topbar from "../components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Foodie-Log",
  description: "Generated by Foodie-Log",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex">
          <LeftSidebar />
          <div className="flex flex-col">
            <Topbar />
            {children}
          </div>
        </div>
        <Bottombar />
      </body>
    </html>
  );
}
